eureka:
  client:
    enabled: false

spring:
  cloud:
    config:
      discovery:
        enabled: false
      override-system-properties: false     # do not override config from microservice
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:QHyCmtc8qthgigNO}

application:
  config:
    jwt:
      secret: ${JWT_SECRET:a00ls1hLRMxTgk0AcrpawYJvR4FDwc07xGyaROb0H6L}