
image:
  repository: confluentinc/cp-kafka
  pullPolicy: IfNotPresent
  tag: latest


service:
  type: ClusterIP
  containerPort: 9092


configMap:
  enabled: true
  data:
    KAFKA_NODE_ID: 1
    KAFKA_PROCESS_ROLES: 'broker,controller'
    KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'
    KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
    KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://ecomm-kafka-service-ecomm-app:80'
    KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
    KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
    CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk' # Any base64 string
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


livenessProbe: null
readinessProbe: null