nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
image:
  repository: heheh123/ecomm-config
  pullPolicy: IfNotPresent
  tag: dev
  digest: sha256:f4489a21b77f1382101913d2024cb473b18e1e0031c4bc84de1a517a4f4a380c
service:
  type: ClusterIP
  port: 8080
configMap:
  enabled: true
  data:
    SPRING_PROFILES_ACTIVE: dev
livenessProbe: null
readinessProbe: null
