nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
image:
  repository: heheh123/ecomm-config
  pullPolicy: IfNotPresent
  tag: dev
  digest: sha256:93c406b205b086e316e93c417fb39b88fee0fe1d1c0e51614dfddffcb8056c56
service:
  type: ClusterIP
  port: 8080
configMap:
  enabled: true
  data:
    SPRING_PROFILES_ACTIVE: dev
livenessProbe: null
readinessProbe: null
