nameOverride: ""
fullnameOverride: ""
podAnnotations: {}

image:
  repository: heheh123/ecomm-config
  pullPolicy: IfNotPresent
  tag: dev
  digest: sha256:b77940acd7f8f3920ea91e3c9fc0b496b3350ae915b30830f9c6bf475493a85b


service:
  type: ClusterIP
  port: 8080


configMap:
  enabled: true
  data:
    SPRING_PROFILES_ACTIVE: dev

livenessProbe: null
readinessProbe: null