create table if not exists address
(
    id integer not null GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street varchar(255),
    house_number varchar(255),
    zip_code varchar(255)
);

create table if not exists users
(
    id integer not null GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name varchar(255),
    last_name varchar(255),
    email varchar(255) unique,
    username varchar(255) unique,
    password varchar(255) not null,
-- mapping/ add relationship between 2 tables
    address_id integer
        constraint fk1_random_text references address
);

-- default increase by 50, if need other value -> have to customize at Entity lv
-- create sequence if not exists address_seq increment by 50;
-- create sequence if not exists user_seq increment by 50;