redis-ha:
  enabled: false

controller:
  replicas: 1

global:
  domain: ""

server:
  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    hostname: ""
    paths:
      - /
  extraArgs:
    - --insecure

repoServer:
  replicas: 1

applicationSet:
  replicas: 1
