spring.application.name=gateway-service
server.port=8080

# Enable service discovery for the gateway
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
# Convert service IDs to lower case -> can use lower-case service IDs from urls
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true