server.port=8080

spring.datasource.url=jdbc:postgresql://ecomm-manual-db.cmjaoi0qwwx8.us-east-1.rds.amazonaws.com:5432/payment_db

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-description="Initial Baseline"
spring.flyway.baseline-version=0
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}


# Kafka server address
spring.kafka.producer.bootstrap-servers=ecomm-kafka-service-ecomm-app
spring.kafka.bootstrap-servers=ecomm-kafka-service-ecomm-app

# configure key & value serializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# pass in "orderConf" as object & provide full package where "orderConf" present
spring.kafka.producer.properties.spring.json.type.mapping=paymentNotification:com.ecmicro.ecommerce.dto.KafkaPaymentNotification