spring.application.name=registry-server

# default eureka port
server.port=8761
eureka.instance.hostname=localhost

# disable fetching registry info from others
eureka.client.fetch-registry=false
# don't want the registry server to register with itself
eureka.client.register-with-eureka=false