create table if not exists orders
(
    id integer not null GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id integer not null,
    created_date timestamp,
    payment_method varchar(255),
    status varchar(255),
    total_price numeric(38, 2)
);

create table if not exists order_items
(
    id integer not null GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity double precision not null,
    prod_id integer not null,
    order_id integer not null
        constraint fk1_random_text references orders
);