spring.application.name=order-service
server.port=8081

spring.config.import=optional:configserver:http://localhost:8888

# later configure with gateway's port
application.config.user-url=http://localhost:8082/api/v1/users
application.config.product-url=http://localhost:8083/api/v1/products
application.config.payment-url=http://localhost:8084/api/v1/payments
