spring.application.name=product-service

# H2 Database
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:prod-sv
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=123


# Force Spring to initialize schema.sql + data.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Optional: see SQL statements in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true