spring.application.name=product-service
server.port=8083
spring.config.import=optional:configserver:http://localhost:8888

###### PostgreSQL Database ####### (syntax: jdbc:postgresql://<host>:<port>/<database_name>)
spring.datasource.url=jdbc:postgresql://localhost:5432/product
spring.datasource.username=hehe
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

######## JPA props ########
#spring.jpa.defer-datasource-initialization=true

# Optional: see SQL statements in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# rely on Flyway for schema management (create schema)
# only validate - do not create or update schema
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database=postgresql
# define dialect - is the SQL variant used by PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

######## Flyway config ########
spring.flyway.enabled=true
# auto call flyway migrations when on non-empty schema
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-description="Initial Baseline"
spring.flyway.baseline-version=0
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}