spring.application.name=config-server
server.port=8888

spring.profiles.include=native

###### config spring cloud config server - native profile ########
# fetch local files from the specified directory, or config files remotely from a git repo
spring.cloud.config.server.native.search-locations=classpath:/configurations,classpath:/configurations/{application}
# where 'classpath' refers to src/main/resources folder (current dir)

