spring.application.name=config-server
server.port=8080

###### config spring cloud config server - native profile ########
# fetch local files from the specified directory, or config files remotely from a git repo
spring.cloud.config.server.native.search-locations=classpath:/configurations,classpath:/configurations/{application}

management.endpoints.web.exposure.include=prometheus