nameOverride: ""
fullnameOverride: ""
podAnnotations: {}

image:
  repository: heheh123/ecomm-gateway
  pullPolicy: IfNotPresent
  tag: dev

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: ecomm-public
  hosts:
    - host: manual-ecommerce.com    # for internal controller routing, havent bought a domain...
      paths:
        - path: /
          pathType: Prefix

configMap:
  enabled: true
  data:
    SPRING_PROFILES_ACTIVE: dev


livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
    initialDelaySeconds: 30
    periodSeconds: 30

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
    initialDelaySeconds: 30
    periodSeconds: 30