spring.application.name=gateway-service

# spring.config.import=optional:configserver:http://configserver:8080

server.port=8080

management.endpoints.web.exposure.include=health
# Show full details (optional, but good for debugging)
management.endpoint.health.show-details=always


# Enable service discovery for the gateway -> gateway can find & route requests to registered services
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
# Convert service IDs to lower case -> can use lower-case service IDs from urls
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# Strip /{serviceId} prefix for discovery-locator routes so identity-service receives /api/v1/identity/**
spring.cloud.gateway.server.webflux.discovery.locator.filters[0]=StripPrefix=1

# Apply JWT auth filter to all routes (including discovery-locator routes)
spring.cloud.gateway.server.webflux.default-filters[0]=AuthFilter


spring.cloud.gateway.server.webflux.routes[0].id=identity-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://IDENTITY-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/identity/**

spring.cloud.gateway.server.webflux.routes[1].id=product-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/products/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=AuthFilter

spring.cloud.gateway.server.webflux.routes[2].id=user-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/users/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=AuthFilter

spring.cloud.gateway.server.webflux.routes[3].id=order-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/orders/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=AuthFilter

spring.cloud.gateway.server.webflux.routes[4].id=payment-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/payments/**
spring.cloud.gateway.server.webflux.routes[4].filters[0]=AuthFilter