spring.application.name=gateway-service

spring.config.import=optional:configserver:http://config-server:8080


eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

spring.cloud.config.discovery.enabled=false
spring.cloud.config.discovery.service-registry.auto-registration.enabled=false

management.endpoints.web.exposure.include=prometheus
