create table if not exists user_credentials
(
    id integer not null GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255) unique,
    username varchar(255) unique,
    password varchar(255) not null
);