name: CICD workflow for [config-server] service

on:
  push:
    paths:
      - ./.github/services/config-server.yaml
    branches:
      # - main
      # - develop
      - cicd
  workflow_dispatch:   # manual trigger


jobs:
  main-workflow:
    name: Call the main workflow
    uses: ./.github/reusable/cicd-test.yaml
    secrets: inherit