name: CICD workflow for [config-server] service

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - services/**
    branches:
      # - main
      # - develop
      - cicd


jobs:
  main-workflow:
    name: Call the main workflow
    uses: nhan-n9/ecommerce-microservices-cicd/.github/workflows/cicd-test.yaml@main
    secrets: inherit
    with:
      SERVICE_NAME: config-server
      IMAGE_NAME: heheh123/ecomm-config
      GIT_REPOSITORY: nhan-n9/ecommerce-microservices
      GIT_BRANCH: cicd