create table if not exists payments
(
    id integer not null GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id integer not null,
    created_date timestamp,
    payment_method varchar(255),
    total_price numeric(38, 2)
);